### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by mdinesh124** [WH0SUMIT/propack#14]
**Describe the solution you'd like**

I would add preloader to the website.

**Comment by mdinesh124** [comment]
Please assign me this issue.

**Comment by yashsehgal** [comment]
Thanks for raising this issue @mdinesh124 💪🏽 
By Preloader, Do you mean to
- Create a Preloader for Propack's website.
- Or, A Preloader component as a project.

**Comment by mdinesh124** [comment]
a preloader for propack's website. After the loader, page will be displayed.

**Comment by yashsehgal** [comment]
> a preloader for propack's website. After the loader, the page will be displayed.

Oh, That's great! We have assigned this issue to you, You can get started! 💯

**Comment by mdinesh124** [comment]
Ok
