### ISSUE TITLE
Add random joke generator

### ISSUE THREAD

**Issue by harshita0802goswami** [WH0SUMIT/propack#20]
**Is your feature request related to a problem? Please describe.**
With the help of API, it will load random jokes on clicking a button

**Describe the solution you'd like**
A mini-project on the random joke generator,it will display random jokes when we click on a button

**Comment by WH0SUMIT** [comment]
Okay, @harshita0802goswami this is a nice project and I'm assigning this issue to you!
All the relevant details about contribution are in the Readme so go through this if you don't know how to implement it, and one more thing are you adding this project under DCP'21 ??

**Comment by harshita0802goswami** [comment]
Yes I am a contributor at DCP'21

**Comment by WH0SUMIT** [comment]
any updates ??

**Comment by harshita0802goswami** [comment]
I couldn't find this issue so I raised the same issue and submitted it also. My PR was also mergerd.
