### ISSUE TITLE
Color Guessing Game

### ISSUE THREAD

**Issue by siddhi-244** [WH0SUMIT/propack#22]
**Is your feature request related to a problem? Please describe.**
no its a new feature.

**Describe the solution you'd like**
i would like to add color guessing game in html,css,js.

![Screenshot (36)](https://user-images.githubusercontent.com/69195262/125190078-fdeb7c80-e258-11eb-8af8-851d11d0c80a.png)

**Comment by siddhi-244** [comment]
please assign me this under dcp

**Comment by WH0SUMIT** [comment]
okay siddhi, I'm assigning this issue to you.
