### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Baba-Yaga-1** [WH0SUMIT/propack#29]
**Is your feature request related to a problem? Please describe.**

Its a new feature/project.

**Describe the solution you'd like**
I would like to add a  Javascript Calculator.

**Comment by Baba-Yaga-1** [comment]
Can you assign me this issue?

**Comment by WH0SUMIT** [comment]
okay, @Baba-Yaga-1 I'm assigning this issue to you can start working on it.
