### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by mdinesh124** [WH0SUMIT/propack#30]
**Describe the solution you'd like**

I would add scroll to top button in home, about, project and contact page.

**Comment by mdinesh124** [comment]
Please assign me this issue.

**Comment by WH0SUMIT** [comment]
@mdinesh124 I want the scroll to top button in the right bottom. make sure the style and color should be matched with our theme.

**Comment by WH0SUMIT** [comment]
are you a participant at DCP'21 ??

**Comment by mdinesh124** [comment]
> are you a participant at DCP'21 ??

Yes

**Comment by mdinesh124** [comment]
> @mdinesh124 I want the scroll to top button in the right bottom. make sure the style and color should be matched with our theme.

Ok

**Comment by WH0SUMIT** [comment]
make sure after every submission you fill the form which I've shared on our discord server as well as on the slack channel!
