### ISSUE TITLE
Update the hover effect in Navbar

### ISSUE THREAD

**Issue by sidparashar2001** [WH0SUMIT/propack#34]
**Is your feature request related to a problem? Please describe.**
The website will look more creative after adding a good hover effect in navbar

**Describe the solution you'd like**
I will add the hover effect in nav bar links

**Describe alternatives you've considered**

**Additional context**

**Comment by sidparashar2001** [comment]
please assign me this issue

**Comment by Naman-mahi** [comment]
Sir, this issue is assign to me.

**Comment by sidparashar2001** [comment]
can you please assign me this issue

**Comment by sidparashar2001** [comment]
@WH0SUMIT please assign me this issue
