### ISSUE TITLE
Add a form with validations in javascript 

### ISSUE THREAD

**Issue by siddhi-244** [WH0SUMIT/propack#35]
**Is your feature request related to a problem? Please describe.**
No it's a new feature.

**Describe the solution you'd like**
I would like to add form validation in js.

**Describe alternatives you've considered**

**Additional context**

**Comment by siddhi-244** [comment]
Assign me this under dcp.

**Comment by WH0SUMIT** [comment]
okay, you can start working on it make sure you'll add all the aspects of javascript form validation. Best of luck!
