### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by WH0SUMIT** [WH0SUMIT/propack#7]
update the Readme file with proper data + gif, website image, and contribution section!

**Comment by deek121477** [comment]
I would like to work on this issue

**Comment by RakeshCharpe** [comment]
Can I work on this issue under DCP'21.

**Comment by WH0SUMIT** [comment]
No @RakeshCharpe This Issue is created before the program has been started so you cannot contribute to it, the actual contribution is started after 10th July!
