### ISSUE TITLE
Javascript StopWatch 

### ISSUE THREAD

**Issue by Baba-Yaga-1** [WH0SUMIT/propack#8]
I am a participant of DevIncept. Can I add a basic JS project ?

**Comment by WH0SUMIT** [comment]
Yes, That is the main factor of ProPack.

**Comment by Baba-Yaga-1** [comment]
So, can I add a js-stopwatch?

**Comment by WH0SUMIT** [comment]
yes you can start working on this project and make sure you'll use issue templates next time, and if haven't joined the discord channel yet then go through the Readme file to join !

**Comment by Baba-Yaga-1** [comment]
Okay, sure.
