### ISSUE TITLE
Age Calculator 

### ISSUE THREAD

**Issue by siddhi-244** [WH0SUMIT/propack#9]
It is a basic age calculator website which can be used  to calculate age in days,months and years. 

Please assign me this under DCP'21

**Comment by WH0SUMIT** [comment]
Describe more on this project like what it is and what it does, then I'll assign it to you! 
and make sure you'll join our discord server so we can plan more features and projects there, the link is in the Readme!

**Comment by siddhi-244** [comment]
> Describe more on this project like what it is and what it does, then I'll assign it to you!
> and make sure you'll join our discord server so we can plan more features and projects there, the link is in the Readme!

Done

**Comment by siddhi-244** [comment]
> Describe more on this project like what it is and what it does, then I'll assign it to you!
> and make sure you'll join our discord server so we can plan more features and projects there, the link is in the Readme!

The discord link is expired

**Comment by WH0SUMIT** [comment]
sorry for the inconvenience, here is the link https://discord.com/invite/NgWxbsAFmW

**Comment by siddhi-244** [comment]
> sorry for the inconvenience, here is the link https://discord.com/invite/NgWxbsAFmW

I have added the description as well !

**Comment by WH0SUMIT** [comment]
yes and I'm assigning this project to you! You can start working on it.

**Comment by siddhi-244** [comment]
Sure.
